### ISSUE TITLE
app_httpd.cpp error: dl_lib.h: No such file or directory

### ISSUE THREAD

**Issue by hoahoctro** [PepeTheFroggie/ESP32CAM_RCTANK#1]
I searched but there is nothing about this lib, can you help ?

**Comment by Pilotgeek45** [comment]
hoahoctro, roll back your espressif libraries to 1.0.2, that worked for me.

**Comment by williamsokol** [comment]
I added a pull request that fixes this, it looks like the Arduino IDE no longer shows this library. 

https://github.com/PepeTheFroggie/ESP32CAM_RCTANK/pull/4

**Comment by PepeTheFroggie** [comment]
Ran into this myself. Solution is to get this whole directory, 
https://github.com/ArduCAM/ArduCAM_ESP32S_UNO_PSRAM/tree/master/tools/sdk/include/esp-face
and store it in the source folder. Then change include to #include "esp-face/dl_lib.h"
